
services:
  api:
    image: chl11wq12/kosta-2-api:v1.0.0
    container_name: api
    platform: linux/amd64
    build: .
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    labels:
      # Traefik 라우팅 설정
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  mysql:
    image: mysql:8
    container_name: mysql
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - backend

  traefik:
    image: traefik:v3.4
    container_name: traefik
    platform: linux/amd64
    ports:
      - 80:80
      - 8080:8080
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    command:
      - "--log.level=DEBUG" # 디버그 모드
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
volumes:
  data:

networks:
  backend:
    driver: bridge
