networks:
  backend:
    driver: bridge

services:
  api-server:
    image: chl11wq12/kosta-2-api-server:v1.0.0
    platform: linux/amd64
    build: .
    container_name: api-server
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      mysql:
        condition: service_healthy  # MySQL이 healthy 상태가 되면 실행
    networks:
      - backend

  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - backend

volumes:
  mysql_data:
